[Do 381] rewrite Gridsome plugins to type script
th2-net/th2-docs pull request #133
Opened 2022-11-08 10:48 UTC by Hdd87

2022-11-11 06:15 UTC, d0rich requested changes
1. JS files compiled from TS to be deleted from the git
2. Commented old code lines to be deleted from TS files
3. Some plugins contain only `any` types. It can be only temporary measure in process of migrating code. It is bad practice to `any` type anywhere. Somewhere types can be reused from other plugins.

2022-11-11 12:32 UTC, d0rich submitted a review, later dismissed

2022-11-15 07:22 UTC, Hdd87 commented
@d0rich there are some conflicts

2022-11-17 10:13 UTC, d0rich approved these changes

2022-11-17 10:13 UTC, merged