[DO-419] migrate to new module design
th2-net/th2-docs pull request #156
Opened 2022-12-12 11:13 UTC by d0rich

2023-03-15 20:04 UTC, lingvolab requested changes

2023-03-15 20:04 UTC, lingvolab commented on src/plugins/gridsome/plugin/create-index/README.md
> +This plugin saves text from markdown to JSON files in order to save this content in ElasticSearch further.
```suggestion
This plugin converts the text from Markdown to JSON to subsequently use this content in ElasticSearch.
```

2023-03-15 20:04 UTC, lingvolab commented on src/plugins/gridsome/plugin/create-index/README.md
> +Every index file stores up to 5 pages with following structure:
```suggestion
Every index file stores up to 5 pages with the following structure:
```

2023-03-15 20:08 UTC, lingvolab commented on content/modules/check2-recon/overview.md
> +**сheck2-recon** is one of the th2 modules.
```suggestion
**check2-recon** is one of the th2 modules. 
```

2023-03-16 12:10 UTC, StanG4313 approved these changes

2023-03-16 12:10 UTC, lingvolab approved these changes

2023-03-16 12:11 UTC, merged